language: go

go:
  - "1.5"

install:
  - go get -u -v github.com/spf13/hugo
  - git clone --depth 1 https://github.com/spf13/hyde.git themes/hyde

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: "barclay.io"
  local_dir: public
  skip_cleanup: true
  region: ap-southeast-2
